In [1]:
import sqlite3 as lite 
import pandas as pd 
import os

#### Note   
In all cases, use only `con.execute` feature and not dataframes.  

##### Create database   
In your folder, create a database named 0101a_lab_\<your folder name>.sqlite   

In [11]:
con = lite.connect(f'0101a_lab_smaranrb.sqlite')

##### Create tables  
Create tables referring to the spreadsheets in Assignments folder for columns names   
- 'Books' using bookset.xlsx   
- 'Users' using userset.xlsx   
- 'Ratings' using ratingset.xlsx  

In [12]:
df1 = pd.read_excel("G:/.shortcut-targets-by-id/1aBWQaFQhja65Ljp3SLszLrSLfIbp0hjJ/DBMS_Course/Assignments/bookset.xlsx")
df2 = pd.read_excel("G:/.shortcut-targets-by-id/1aBWQaFQhja65Ljp3SLszLrSLfIbp0hjJ/DBMS_Course/Assignments/userset.xlsx")
df3 = pd.read_excel("G:/.shortcut-targets-by-id/1aBWQaFQhja65Ljp3SLszLrSLfIbp0hjJ/DBMS_Course/Assignments/ratingset.xlsx")

In [13]:
df1.to_sql('books', con, index = False)
df2.to_sql('users', con, index = False)
df3.to_sql('ratings', con, index = False)

5

Verify

In [14]:
con.execute("select * from books").fetchall()

[(195153448,
  'Classical Mythology',
  'Mark P. O. Morford',
  2002,
  'Oxford University Press'),
 (1841721522,
  'New Vegetarian: Bold and Beautiful Recipes for Every Occasion',
  'Celia Brooks Brown',
  2001,
  'Ryland Peters and  Small Ltd'),
 (375759778,
  'Prague : A Novel',
  'ARTHUR PHILLIPS',
  2003,
  'Random House Trade Paperbacks'),
 (425163091,
  'Chocolate Jesus',
  'Stephan Jaramillo',
  1998,
  'Berkley Publishing Group')]

In [15]:
con.execute("select * from users").fetchall()

[(2, 'stockton, california, usa', 18),
 (4, 'porto, v.n.gaia, portugal', 17),
 (6, 'santa monica, california, usa', 61),
 (10, 'albacete, wisconsin, spain', 26),
 (11, 'melbourne, victoria, australia', 14),
 (13, 'barcelona, barcelona, spain', 26),
 (18, 'rio de janeiro, rio de janeiro, brazil', 25),
 (19, 'weston, ,', 14),
 (20, 'langhorne, pennsylvania, usa', 19)]

In [16]:
con.execute("select * from ratings").fetchall()

[(2, 195153448, 0),
 (10, 1841721522, 0),
 (10, 8477024456, 6),
 (19, 375759778, 7),
 (20, 425163091, 0)]

##### Insert Data  
  
1. Insert a row each with con.execute.   
	Verify   
2. Delete these rows from the tables.   
    Verify   
3. Insert all the rows in each of the tables using con.executemany    
	Verify  
4. Delete the rows from all the tables. 	   
	Verify    
5. Create one text file with script to insert every row	in the three tables.   
6. Using one con.executescript, insert rows into all the three tables    
	Verify  

Deleting all rows from table books

In [17]:
con.execute('delete from books')

In [19]:
con.execute('select * from books').fetchall()

[]

Inserting a row into table books

In [20]:
con.execute('insert into books values (195153448 , "Classical Mythology", "Mark P. O. Morford", 2002, "Oxford University Press")')

In [21]:
con.execute('select * from books').fetchall()

[(195153448,
  'Classical Mythology',
  'Mark P. O. Morford',
  2002,
  'Oxford University Press')]

In [22]:
# Deleting all rows again
con.execute('delete from books')

executemeny

In [24]:
query = '''insert into books values (?,?,?,?,?)'''
list_data = [(195153448,
  'Classical Mythology',
  'Mark P. O. Morford',
  2002,
  'Oxford University Press'),
 (1841721522,
  'New Vegetarian: Bold and Beautiful Recipes for Every Occasion',
  'Celia Brooks Brown',
  2001,
  'Ryland Peters and  Small Ltd'),
 (375759778,
  'Prague : A Novel',
  'ARTHUR PHILLIPS',
  2003,
  'Random House Trade Paperbacks'),
 (425163091,
  'Chocolate Jesus',
  'Stephan Jaramillo',
  1998,
  'Berkley Publishing Group')]
con.executemany(query, list_data)

In [26]:
con.execute('select * from books').fetchall()

[(195153448,
  'Classical Mythology',
  'Mark P. O. Morford',
  2002,
  'Oxford University Press'),
 (1841721522,
  'New Vegetarian: Bold and Beautiful Recipes for Every Occasion',
  'Celia Brooks Brown',
  2001,
  'Ryland Peters and  Small Ltd'),
 (375759778,
  'Prague : A Novel',
  'ARTHUR PHILLIPS',
  2003,
  'Random House Trade Paperbacks'),
 (425163091,
  'Chocolate Jesus',
  'Stephan Jaramillo',
  1998,
  'Berkley Publishing Group')]

In [27]:
# Deleting it.... AGAIN...
con.execute('delete from books')

In [28]:
con.execute('select * from books').fetchall()

[]

executescript

Text file (script.txt) contents:

INSERT INTO BOOKS VALUES(195153448,  'Classical Mythology',  'Mark P. O. Morford',   2002,  'Oxford University Press')

INSERT INTO BOOKS VALUES(1841721522,  'New Vegetarian: Bold and Beautiful Recipes for Every Occasion',  'Celia Brooks Brown',  2001,  'Ryland Peters and  Small Ltd')

INSERT INTO BOOKS VALUES(375759778,  'Prague : A Novel',  'ARTHUR PHILLIPS',  2003,  'Random House Trade Paperbacks')

INSERT INTO BOOKS VALUES(425163091,  'Chocolate Jesus',  'Stephan Jaramillo',  1998,  'Berkley Publishing Group')


In [30]:
help(con.executescript)

Help on built-in function executescript:

executescript(sql_script, /) method of sqlite3.Connection instance
    Executes multiple SQL statements at once.



In [31]:
con.executescript('script.sql')

OperationalError: near "script": syntax error

In [9]:
con.close()