# -*- coding: utf-8 -*-
"""0501_lab_sumedhal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10TrFZRC_9Riqg4RI-DnJsIqa1htbwnlb

#### 0501_Lab  
1. Cleanse categorical data in the Student table in BTech22_\<your name\>.sqlite.
"""

import sqlite3 as lite
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

con = lite.connect('/content/drive/MyDrive/sumedhal/BTech22_sumedhal.sqlite')

from os import replace
df = pd.read_excel('/content/drive/MyDrive/DBMS_Course/Data/BTech22 Data.xlsx')
con.execute("DROP TABLE IF EXISTS Students")
df.to_sql('Students',con,index = False)

"""2. Create look-up tables (aka master tables) for states, towns, and languages.    
Insert data.     
See [RTO Codes](https://www.v3cars.com/car-guide/state-code-regional-transport-office-rto-india) and
Census Codes for [States and Cities](https://censusindia.gov.in/nada/index.php/catalog/42648) and
[Language Codes](https://censusindia.gov.in/nada/index.php/catalog/42561)  
Use standard codes or abbreviations as PK.  


"""

con.execute("SELECT * FROM sqlite_master").fetchall()

sql1 = """
    UPDATE Students
    SET Home_State = TRIM(Home_State)
"""
sql2 = """
    UPDATE Students
    SET Home_State = 'Karnataka'
    WHERE Home_State IN
    ('karnataka','KARNATAKA','karntaka','KARnataka','Karantaka')
"""
sql3 = """
    UPDATE Students
    SET Home_State = 'Unknown'
    WHERE Home_State = 'Nil'
"""

con.execute(sql1)

con.execute(sql2)

con.execute(sql3)

con.commit()

con.execute('DROP TABLE IF EXISTS Master_State')
con.execute("CREATE TABLE Master_State(State TEXT Primary Key, Code TEXT)")

rows = [('Karnataka','KA'),
 ('Jammu','JK'),
 ('Haryana','HR'),
 ('Delhi','DL'),
 ('West Bengal','WB'),
 ('Andhra Pradesh','AP'),
 ('Telangana','TS'),
 ('Punjab','PB'),
 ('Goa','GA'),
 ('Uttar Pradesh','UP'),
 ('Rajasthan','RJ'),
 ('Tamil Nadu','TN'),
 ('Bihar','BR'),
 ('None','-1'),
 ('Gujarat','GJ'),
 ('Jharkhand','JH')]

con.executemany("INSERT INTO Master_State(State,Code) VALUES(?,?)",rows)

pd.read_sql("SELECT * FROM Master_State",con)

con.execute("DROP TABLE IF EXISTS Master_City")
con.execute("CREATE TABLE Master_City(city TEXT Primary Key, State_Code TEXT, District_code TEXT)")

rows1 = [('Mysuru',577, 5572),
 ('Bengaluru',572,000),
 ('Bidar',574,5558),
 ('Bathindi',0,0),
 ('Ballari',572,54432),
 ('Raichur',559,000),
 ('Hubballi',562,5475),
 ('Mandya',573,550),
 ('Chitradurga',566,000),
 ('Kalaburgi',677,2322),
 ('Maahishmati',720,13455),
 ('Hosapete',554,23111),
 ('New Delhi',1,000),
 ('Dharwad',563,65443),
 ('Kolkata',456,12364),
 ('Tirupati',245,13453),
 ('Chikkamagaluru',533,4546),
 ('Shivamogga',523,12253),
 ('Hyderabad',252,6553),
 ('Adoni',765,3312),
 ('Nagoor',332,75234),
 ('Amritsar',124,32345),
 ('Goa',597,6536),
 ('Bidadi',553,13443),
 ('Saharanpur',311,564),
 ('Abu Road',00,00),
 ('Chennai',653,13354),
 ('Haveri',524,43543),
 ('Yadgir',592,93489),
 ('Tumkur',642,45211),
 ('Dharbanga',674,7653),
 ('Davengere',906,46222),
 ('None',00,00),
 ('Lucknow',567,13534),
 ('Chikkaballapur',876,56533),
 ('Gangavathi',977,3132),
 ('Vijayapuraa',564,1329),
 ('Ahmedabad',1333,6756),
 ('Chittoor',233,5676),
 ('Mudigere',133,65655),
 ('Kolar',454,43544),
 ('Gajendragad',565,2323),
 ('Jamshedpur',565,7654),
 ('Belagavi',554,5643),
 ('Hassan',243,56765),
 ('Mangalore',231,56754),
 ('Magadi',654,24353),
 ('Ananthapur',657,2345),
 ('Vijayapura',765,52324),
 ('Jaipur',675,23475)]

con.executemany("INSERT INTO Master_City(city,State_Code,District_code) VALUES(?,?,?)",rows1)

pd.read_sql("SELECT * FROM Master_City",con)

con.execute("DROP TABLE IF EXISTS Master_Lang")
con.execute("CREATE TABLE Master_Lang(Language TEXT Primary Key, Code TEXT)")

row2 = [('Telugu','te'),
 ('English','en'),
 ('Marathi','mr'),
 ('Urdu','ur'),
 ('Kannada','kn'),
 ('Hindi','hi'),
 ('Hinglish','he'),
 ('Konkani','kok'),
 ('Tamil','ta'),
 ('Malayalam','ml'),
 ('Tulu','tl'),
 ('Gujarati','gu'),
 ('Punjabi','pa')]

con.executemany("INSERT INTO Master_lang(language,Code) VALUES(?,?)",row2)

"""3. Create tables for electives and clubs.  
    Their PK may be auto-incremented.  
    Insert data.  
"""

query = """
    UPDATE Students
    SET Home_State = TRIM(elective)
"""
con.execute(query)

ele = [(1,'Photography '),
 (2,'Community service '),(3,'Drumming'),(4,'Indian Knowledge System: Mathematica and Ayurveda'),
 (5,'Success, Happiness and Leadership'),
 (6,'Hindusthani Vocals'),
 (7,'Contemporary dance '),(8,'Mixed martial arts'),(9,'Kuchipudi'),]

con.execute("DROP TABLE IF EXISTS Master_Elective")
con.execute("CREATE TABLE Master_Elective(ID INT AUTO_INCREMENT, elective_name TEXT)")

con.executemany("INSERT INTO Master_Elective(ID,elective_name) VALUES(?,?)",ele)

pd.read_sql("SELECT * FROM Master_Elective",con)

club = [(1,'cybersecurity'), (2,'Neural Nexus') ,(3,'Viksha'),(4,'callisto astronomy club'),(5,'ಶ್ರೀಗಂಧ'),(6,'Possessor Architecture'),(7,'carvaccess(rvce)'),(8,'E-cell'),(9,'expressions'), (10,'Raag'), (11,'generative AI'),(12,'Q-Pulse',),
 (13,'Rowlings Elf',),(14,'Socials'),(15,'AMEYA'),(16,'Debsoc'),(17,'Happy tails')]
con.execute("DROP TABLE IF EXISTS Master_Clubs")
con.execute("CREATE TABLE Master_Clubs(ID INT PK AUTO_INCREMENT, club_name TEXT)")
con.executemany("INSERT INTO Master_Clubs(ID,club_name) VALUES(?,?)",club)

pd.read_sql("SELECT * FROM Master_Clubs",con)

con.commit()

con.close()

